table VRM_Report
	lineageTag: 5b6fe689-04ee-4728-823e-20bb0b2320e5

	measure 'Total Vulnerabilities' = COUNTROWS('VRM_Report')
		lineageTag: cb55eb1e-ff81-4f62-8da0-b4caef70199f

	measure 'Unique CVEs' = DISTINCTCOUNT('VRM_Report'[CVE#])
		lineageTag: ace5e083-2dd5-4ea3-8784-33638e338616

	measure 'Critical Count' = CALCULATE(COUNTROWS('VRM_Report'), 'VRM_Report'[Criticality] = "Critical")
		lineageTag: e584da08-78f2-4286-a417-2735c8a856ae

	measure 'High Count' = CALCULATE(COUNTROWS('VRM_Report'), 'VRM_Report'[Criticality] = "High")
		lineageTag: 5e7688e3-e8b5-4803-8a81-795122c0d749

	measure 'Exploitable Count' = CALCULATE(COUNTROWS('VRM_Report'), 'VRM_Report'[Criticality] = "Exploitable")
		lineageTag: 5d7efa65-24a1-454b-95b7-b7edb856922e

	measure 'Medium Count' = CALCULATE(COUNTROWS('VRM_Report'), 'VRM_Report'[Criticality] = "Medium")
		lineageTag: 0bda4a8d-811b-407c-a8cd-ee6309681eb0

	measure 'Low Count' = CALCULATE(COUNTROWS('VRM_Report'), 'VRM_Report'[Criticality] = "Low")
		lineageTag: 6ad1e94c-499d-48d8-bb76-3cd1d2a0c2b0

	measure 'Patched Count' = CALCULATE(COUNTROWS('VRM_Report'), 'VRM_Report'[Status] = "Patched")
		lineageTag: 364ab0c1-e8b5-4537-9f51-b0c7e6adf52e

	measure 'Pending Under 1 Month' = CALCULATE(COUNTROWS('VRM_Report'), 'VRM_Report'[Status] = "Pending < 1 month")
		lineageTag: 6cb9bffd-76b9-415d-a159-2bd17e63a0a7

	measure 'Pending Over 1 Month' = CALCULATE(COUNTROWS('VRM_Report'), 'VRM_Report'[Status] = "Pending > 1 month")
		lineageTag: 4cd6bf2e-f788-45a8-846b-e5d36cfec69f

	measure 'Pending Over 2 Months' = CALCULATE(COUNTROWS('VRM_Report'), 'VRM_Report'[Status] = "Pending > 2 months")
		lineageTag: 21c2b682-3c4d-4e54-af84-ce75568f74bc

	measure 'Pending Over 3 Months' = CALCULATE(COUNTROWS('VRM_Report'), 'VRM_Report'[Status] = "Pending > 3 months")
		lineageTag: a18c842e-1e96-43c3-b567-3599863e0f72

	measure 'Risk Accepted Count' = CALCULATE(COUNTROWS('VRM_Report'), 'VRM_Report'[Risk Acceptance] = "Yes")
		lineageTag: 106a2bcf-2730-4555-944f-bc4b5ef6d7f6

	measure 'Risk Accepted Pct' = DIVIDE([Risk Accepted Count], [Total Vulnerabilities], 0)
		lineageTag: a349b805-aaf9-4301-9700-7573712e9e53

	measure 'Average CVSS' = AVERAGE('VRM_Report'[CVSS Score])
		lineageTag: 75b0a418-4992-4dbc-aab9-bcd62018f29d

	measure 'Critical or Exploitable Unpatched' =
			CALCULATE(
			    COUNTROWS('VRM_Report'),
			    'VRM_Report'[Criticality] IN {"Critical", "Exploitable"},
			    'VRM_Report'[Status] <> "Patched"
			)
		lineageTag: 114b13fc-bead-425c-801a-8bac37b94f08

	measure 'Overdue Over 90 Days' = CALCULATE(COUNTROWS('VRM_Report'), 'VRM_Report'[Status] = "Pending > 3 months")
		lineageTag: 9b535629-1be7-4d0e-95ba-4ed0400129cd

	measure 'Avg Days Open' =
			AVERAGEX(
			    FILTER('VRM_Report', 'VRM_Report'[Status] <> "Patched"),
			    DATEDIFF('VRM_Report'[Date First Detected], TODAY(), DAY)
			)
		lineageTag: a5df4ce8-e019-4c6e-8b05-d6ef7fc9dab6

	column 'Unique ID'
		dataType: string
		lineageTag: 9582e1fc-838e-4262-8eeb-0deadab21a5a
		summarizeBy: none
		sourceColumn: Unique ID

	column Criticality
		dataType: string
		lineageTag: 3cb032a2-794f-4778-ba3b-5c77059cffd3
		summarizeBy: none
		sourceColumn: Criticality

	column CVE#
		dataType: string
		lineageTag: b4845840-bef1-4b64-8dca-129cf9d1755f
		summarizeBy: none
		sourceColumn: CVE#

	column 'CVSS Score'
		dataType: double
		lineageTag: 77edae5f-8c87-44bf-af4e-a83d715b02ca
		summarizeBy: sum
		sourceColumn: CVSS Score

		annotation SummarizationSetBy = Automatic

	column Description
		dataType: string
		lineageTag: 50e53dbd-8a1d-4fd2-9680-a7d3b2444cd6
		summarizeBy: none
		sourceColumn: Description

	column 'Device OS'
		dataType: string
		lineageTag: 0bac40f7-35a3-4748-b174-a684d7769ce0
		summarizeBy: none
		sourceColumn: Device OS

	column 'Device Type'
		dataType: string
		lineageTag: ff9ccada-2470-434c-8dca-c2c1e0ecb781
		summarizeBy: none
		sourceColumn: Device Type

	column 'Date First Detected'
		dataType: dateTime
		formatString: Long Date
		lineageTag: ce8d0300-dfda-4379-81c3-fccffcdc9e41
		summarizeBy: none
		sourceColumn: Date First Detected

		variation Variation
			isDefault
			relationship: 8c5808c9-09a6-472c-880e-6ee7d484c83a
			defaultHierarchy: LocalDateTable_804f312d-c6a9-48cb-bba1-4b5c2117af12.'Date Hierarchy'

		annotation UnderlyingDateTimeDataType = Date

	column 'Date Last Detected'
		dataType: dateTime
		formatString: Long Date
		lineageTag: 21aeabfc-982a-4545-9f64-7e2a2d4f64a3
		summarizeBy: none
		sourceColumn: Date Last Detected

		variation Variation
			isDefault
			relationship: 390d455f-faf5-473a-b786-2b68ef53f1ef
			defaultHierarchy: LocalDateTable_f7c60437-cad7-4a95-945e-de2ec1494d24.'Date Hierarchy'

		annotation UnderlyingDateTimeDataType = Date

	column Status
		dataType: string
		lineageTag: 6f906065-4203-4676-84ab-9d2f2962f7ca
		summarizeBy: none
		sourceColumn: Status

	column 'Risk Acceptance'
		dataType: string
		lineageTag: 35bf4ba7-7ba4-4770-b21e-515b141690c0
		summarizeBy: none
		sourceColumn: Risk Acceptance

	column 'Asset Criticality'
		dataType: string
		lineageTag: c42d8d8e-e2c0-4dc0-b2ee-6d27a2342687
		summarizeBy: none
		sourceColumn: Asset Criticality

	column 'Data Type'
		dataType: string
		lineageTag: 24057571-ceda-4996-8a98-a4f57ebc4b1e
		summarizeBy: none
		sourceColumn: Data Type

	column Location
		dataType: string
		lineageTag: 0e5d6476-d691-4c22-afe8-e1c379f26432
		summarizeBy: none
		sourceColumn: Location

	column Notes
		dataType: string
		lineageTag: c95b0f7b-6649-4851-b7be-d4f1c24fb0ba
		summarizeBy: none
		sourceColumn: Notes

	column Product
		dataType: string
		lineageTag: a5b927cf-954c-4d4e-9816-3251f9656df4
		summarizeBy: none
		sourceColumn: Product

	partition VRM_Report-partition = m
		mode: import
		source =
				// ============================================================================
				// VRM_Report (CSV)  –  Final report table  (columns A – O)
				// ============================================================================
				// CSV-mode variant.  The Defender portal Weaknesses export is CVE-level
				// (one row per vulnerability, not per machine×CVE), so this query produces
				// one row per CVE.  The Machines_CSV table is loaded as a supplementary
				// reference for device-fleet statistics but cannot be joined per-row since
				// the portal export does not include a machine-to-CVE mapping.
				//
				// Depends on: Vulnerabilities (CSV override), Enrichment, EnrichmentDefaults
				// ============================================================================
				
				let
				    // ── 0.  Load source queries ─────────────────────────────────────────
				    Vulns    = Vulnerabilities,
				    Defaults = EnrichmentDefaults,
				
				    // ── 1.  Add row index for Unique ID ─────────────────────────────────
				    Indexed = Table.AddIndexColumn(Vulns, "RowNum", 1, 1, Int64.Type),
				
				    // ── 2.  Compute derived columns (A – O) ────────────────────────────
				
				    // --- Column A: Unique ID ---
				    AddUniqueId = Table.AddColumn(Indexed, "A_UniqueId",
				        each Text.From([RowNum]), type text),
				
				    // --- Column B: Criticality ---
				    AddCriticality = Table.AddColumn(AddUniqueId, "B_Criticality", each
				        if [#"Has Exploit"] = "True" then "Exploitable"
				        else if [Severity] = "Critical" then "Critical"
				        else if [Severity] = "High"     then "High"
				        else if [Severity] = "Medium"   then "Medium"
				        else "Low",
				        type text),
				
				    // --- Column C: CVE# / CVSS ---
				    AddCveId = Table.AddColumn(AddCriticality, "C_CveId",
				        each [Name], type text),
				    AddCvss  = Table.AddColumn(AddCveId, "C_CvssScore",
				        each [#"CVSS v3"], type number),
				
				    // --- Column D: Description ---
				    AddDesc = Table.AddColumn(AddCvss, "D_Description",
				        each [Description], type text),
				
				    // --- Column E: Device OS ---
				    // Per-device OS is not available in CVE-level export; show exposed count
				    AddOS = Table.AddColumn(AddDesc, "E_DeviceOS", each
				        let n = try [#"Exposed Machines"] otherwise 0 in
				        if n = 1 then "1 device"
				        else Text.From(n) & " devices",
				        type text),
				
				    // --- Column F: Device Type  (from enrichment defaults) ---
				    AddDeviceType = Table.AddColumn(AddOS, "F_DeviceType", each
				        Defaults[DeviceType],
				        type text),
				
				    // --- Column G: Date First Detected ---
				    AddFirstDetected = Table.AddColumn(AddDeviceType, "G_DateFirstDetected", each
				        [#"First detected"],
				        type date),
				
				    // --- Column H: Date Last Detected ---
				    AddLastDetected = Table.AddColumn(AddFirstDetected, "H_DateLastDetected", each
				        [Updated],
				        type date),
				
				    // --- Column I: Status  (aging bucket from Age (days) column) ---
				    AddStatus = Table.AddColumn(AddLastDetected, "I_Status", each
				        let st = [Status] ?? "" in
				        if st = "NoActionRequired" or st = "Resolved" then "Patched"
				        else
				            let days = try [#"Age (days)"] otherwise 0 in
				            if days > 90 then "Pending > 3 months"
				            else if days > 60 then "Pending > 2 months"
				            else if days > 30 then "Pending > 1 month"
				            else "Pending < 1 month",
				        type text),
				
				    // --- Column J: Risk Acceptance ---
				    AddRisk = Table.AddColumn(AddStatus, "J_RiskAcceptance", each
				        let st = [Status] ?? "" in
				        if st = "Exception" or st = "UnderException" or st = "PartialException"
				        then "Yes" else "No",
				        type text),
				
				    // --- Column K: Asset Criticality  (enrichment defaults) ---
				    AddAssetCrit = Table.AddColumn(AddRisk, "K_AssetCriticality", each
				        Defaults[AssetCriticality],
				        type text),
				
				    // --- Column L: Data Type ---
				    AddDataType = Table.AddColumn(AddAssetCrit, "L_DataType", each
				        Defaults[DataType],
				        type text),
				
				    // --- Column M: Location ---
				    AddLocation = Table.AddColumn(AddDataType, "M_Location", each
				        Defaults[Location],
				        type text),
				
				    // --- Column N: Notes ---
				    AddNotes = Table.AddColumn(AddLocation, "N_Notes", each
				        "", type text),
				
				    // --- Column O: Product ---
				    AddProduct = Table.AddColumn(AddNotes, "O_Product", each
				        [#"Related Software"] ?? "",
				        type text),
				
				    // ── 3.  Select only the final report columns ───────────────────────
				    FinalColumns = Table.SelectColumns(AddProduct, {
				        "A_UniqueId", "B_Criticality", "C_CveId", "C_CvssScore",
				        "D_Description", "E_DeviceOS", "F_DeviceType",
				        "G_DateFirstDetected", "H_DateLastDetected",
				        "I_Status", "J_RiskAcceptance",
				        "K_AssetCriticality", "L_DataType", "M_Location",
				        "N_Notes", "O_Product"
				    }),
				
				    Renamed = Table.RenameColumns(FinalColumns, {
				        {"A_UniqueId",          "Unique ID"},
				        {"B_Criticality",       "Criticality"},
				        {"C_CveId",             "CVE#"},
				        {"C_CvssScore",         "CVSS Score"},
				        {"D_Description",       "Description"},
				        {"E_DeviceOS",          "Device OS"},
				        {"F_DeviceType",        "Device Type"},
				        {"G_DateFirstDetected", "Date First Detected"},
				        {"H_DateLastDetected",  "Date Last Detected"},
				        {"I_Status",            "Status"},
				        {"J_RiskAcceptance",    "Risk Acceptance"},
				        {"K_AssetCriticality",  "Asset Criticality"},
				        {"L_DataType",          "Data Type"},
				        {"M_Location",          "Location"},
				        {"N_Notes",             "Notes"},
				        {"O_Product",           "Product"}
				    })
				in
				    Renamed

