table VRM_Report
	lineageTag: a7549d9c-8c3f-4da0-b967-1de84b4a137e

	measure 'Total Vulnerabilities' = COUNTROWS('VRM_Report')
		lineageTag: 55757269-edfb-4132-8dcd-e56450a0cc70

	measure 'Unique CVEs' = DISTINCTCOUNT('VRM_Report'[CVE#])
		lineageTag: b2930377-314f-4f81-b329-1b0ee6b28387

	measure 'Unique Machines' = DISTINCTCOUNT('VRM_Report'[Machine Name])
		lineageTag: 657f4fa2-0657-4dd7-93fd-2ac09a99d228

	measure 'Critical Count' = CALCULATE(COUNTROWS('VRM_Report'), 'VRM_Report'[Criticality] = "Critical")
		lineageTag: dfd14946-b9b6-40e1-ad49-5517f6afc7cc

	measure 'High Count' = CALCULATE(COUNTROWS('VRM_Report'), 'VRM_Report'[Criticality] = "High")
		lineageTag: 938e977b-d82e-4799-ac5e-94e21c1e474f

	measure 'Exploitable Count' = CALCULATE(COUNTROWS('VRM_Report'), 'VRM_Report'[Criticality] = "Exploitable")
		lineageTag: cb40cdc2-a643-4368-b4d5-e404a1eb759b

	measure 'Medium Count' = CALCULATE(COUNTROWS('VRM_Report'), 'VRM_Report'[Criticality] = "Medium")
		lineageTag: c03e6ff6-c211-457e-a934-52dc737aead7

	measure 'Low Count' = CALCULATE(COUNTROWS('VRM_Report'), 'VRM_Report'[Criticality] = "Low")
		lineageTag: d9d95f1b-37af-4c8f-b196-2343873ee7bc

	measure 'Patched Count' = CALCULATE(COUNTROWS('VRM_Report'), 'VRM_Report'[Status] = "Patched")
		lineageTag: 4233b96f-ee07-40f5-ba1c-217ac84e7b16

	measure 'Pending Under 1 Month' = CALCULATE(COUNTROWS('VRM_Report'), 'VRM_Report'[Status] = "Pending < 1 month")
		lineageTag: d5a430a4-e531-43e0-900f-b48f4c65f218

	measure 'Pending Over 1 Month' = CALCULATE(COUNTROWS('VRM_Report'), 'VRM_Report'[Status] = "Pending > 1 month")
		lineageTag: bceb6a08-017e-4e7f-83ba-3d55650e83b8

	measure 'Pending Over 2 Months' = CALCULATE(COUNTROWS('VRM_Report'), 'VRM_Report'[Status] = "Pending > 2 months")
		lineageTag: d1063c2f-4357-429c-bd78-4b84489b34ff

	measure 'Pending Over 3 Months' = CALCULATE(COUNTROWS('VRM_Report'), 'VRM_Report'[Status] = "Pending > 3 months")
		lineageTag: 284f1d5b-21d9-4b6c-89e4-4e02731ed300

	measure 'Risk Accepted Count' = CALCULATE(COUNTROWS('VRM_Report'), 'VRM_Report'[Risk Acceptance] = "Yes")
		lineageTag: 0d49a11e-a816-4db0-8ae4-31a7b3e57fa9

	measure 'Risk Accepted Pct' = DIVIDE([Risk Accepted Count], [Total Vulnerabilities], 0)
		lineageTag: c4b576ce-2b47-4e8d-afa1-4ff5dfa9da85

	measure 'Average CVSS' = AVERAGE('VRM_Report'[CVSS Score])
		lineageTag: 2a68987f-39c1-434a-82c1-0bb6eb5c30ea

	measure 'Critical or Exploitable Unpatched' =
			CALCULATE(
			    COUNTROWS('VRM_Report'),
			    'VRM_Report'[Criticality] IN {"Critical", "Exploitable"},
			    'VRM_Report'[Status] <> "Patched"
			)
		lineageTag: 52856801-5732-4463-8384-a6c39613415d

	measure 'Overdue Over 90 Days' = CALCULATE(COUNTROWS('VRM_Report'), 'VRM_Report'[Status] = "Pending > 3 months")
		lineageTag: e9adf86e-f451-47e6-9f57-678267d42248

	measure 'Avg Days Open' =
			AVERAGEX(
			    FILTER('VRM_Report', 'VRM_Report'[Status] <> "Patched"),
			    DATEDIFF('VRM_Report'[Date First Detected], TODAY(), DAY)
			)
		lineageTag: 69d9557b-55e3-40cb-967a-c75eb2e10788

	column 'Unique ID'
		dataType: string
		lineageTag: 86cb5c5b-03b1-48b0-af90-64b3cc2d6047
		summarizeBy: none
		sourceColumn: Unique ID

	column Criticality
		dataType: string
		lineageTag: a5253279-42f9-4ff7-9f1b-d7e95a25e499
		summarizeBy: none
		sourceColumn: Criticality

	column CVE#
		dataType: string
		lineageTag: 05a587e0-519e-4eda-b927-829771def19d
		summarizeBy: none
		sourceColumn: CVE#

	column 'CVSS Score'
		dataType: double
		lineageTag: 998ecb19-0643-44ea-b2e8-fefaa7c04d6a
		summarizeBy: none
		sourceColumn: CVSS Score

	column Description
		dataType: string
		lineageTag: b74b2747-a3b5-460c-abbc-2b85f94d3d2b
		summarizeBy: none
		sourceColumn: Description

	column 'Device OS'
		dataType: string
		lineageTag: c3f7bde2-6907-4a32-8973-fa44e0a55db7
		summarizeBy: none
		sourceColumn: Device OS

	column 'Device Type'
		dataType: string
		lineageTag: 8851dd56-9a09-4415-bad6-ddf29deea5c9
		summarizeBy: none
		sourceColumn: Device Type

	column 'Date First Detected'
		dataType: dateTime
		formatString: General Date
		lineageTag: 6d4a37fe-8946-4303-8bcf-3e190e52633f
		summarizeBy: none
		sourceColumn: Date First Detected

	column 'Date Last Detected'
		dataType: dateTime
		formatString: General Date
		lineageTag: 27f2db70-7d51-4f9a-a6d1-10ecd13f269b
		summarizeBy: none
		sourceColumn: Date Last Detected

	column Status
		dataType: string
		lineageTag: f4c43a49-885c-4f7f-a3c5-b32246c09213
		summarizeBy: none
		sourceColumn: Status

	column 'Risk Acceptance'
		dataType: string
		lineageTag: 34706f4a-7d6c-471a-8dab-eadc9d27af97
		summarizeBy: none
		sourceColumn: Risk Acceptance

	column 'Asset Criticality'
		dataType: string
		lineageTag: 3f019686-a330-4865-85fc-a3194f0520ab
		summarizeBy: none
		sourceColumn: Asset Criticality

	column 'Data Type'
		dataType: string
		lineageTag: 14154ad1-9ec9-4392-9e8a-5d3bcdc70c85
		summarizeBy: none
		sourceColumn: Data Type

	column Location
		dataType: string
		lineageTag: 7d16a414-3ec6-4a59-abb0-dad0ae949d5c
		summarizeBy: none
		sourceColumn: Location

	column Notes
		dataType: string
		lineageTag: 75ae87cd-e110-4826-9c33-71c68c68d7c7
		summarizeBy: none
		sourceColumn: Notes

	column Product
		dataType: string
		lineageTag: 9d539cd5-8804-4cc6-ba48-f7633985ba2e
		summarizeBy: none
		sourceColumn: Product

	column 'Machine Name'
		dataType: string
		lineageTag: a0d9f43d-5617-4660-ad00-881080c27f60
		summarizeBy: none
		sourceColumn: Machine Name

	partition VRM_Report-partition = m
		mode: import
		source =
				// ============================================================================
				// VRM_Report  –  Final report table  (columns A – O)
				// ============================================================================
				// Joins MachineVulnerabilities × Vulnerabilities × Machines × Enrichment and
				// computes every derived column exactly as the TypeScript mapper does.
				//
				// Depends on queries:
				//   MachineVulnerabilities, Vulnerabilities, Machines,
				//   Enrichment, EnrichmentDefaults, fn_PaginatedGet
				// ============================================================================
				
				let
				    // ── 0.  Load source queries ─────────────────────────────────────────
				    MV       = MachineVulnerabilities,
				    Vulns    = Vulnerabilities,
				    Machines = Machines,
				    Enrich   = Enrichment,
				    Defaults = EnrichmentDefaults,
				
				    // ── 1.  Join MachineVulnerabilities → Vulnerabilities on cveId ──────
				    JoinVuln = Table.NestedJoin(
				        MV, {"cveId"}, Vulns, {"id"}, "vuln", JoinKind.Inner
				    ),
				    ExpandVuln = Table.ExpandTableColumn(JoinVuln, "vuln", {
				        "description", "severity", "cvssV3", "publishedOn", "updatedOn",
				        "firstDetected", "publicExploit", "exploitVerified", "status"
				    }, {
				        "v.description", "v.severity", "v.cvssV3", "v.publishedOn",
				        "v.updatedOn", "v.firstDetected", "v.publicExploit",
				        "v.exploitVerified", "v.status"
				    }),
				
				    // ── 2.  Join → Machines on machineId for OS / hostname ─────────────
				    JoinMachine = Table.NestedJoin(
				        ExpandVuln, {"machineId"}, Machines, {"id"}, "machine", JoinKind.LeftOuter
				    ),
				    ExpandMachine = Table.ExpandTableColumn(JoinMachine, "machine", {
				        "computerDnsName", "osPlatform", "rbacGroupName", "lastIpAddress"
				    }, {
				        "m.computerDnsName", "m.osPlatform", "m.rbacGroupName", "m.lastIpAddress"
				    }),
				
				    // ── 3.  Join → Enrichment  (try hostname, then rbacGroup) ──────────
				    //        Hostname match
				    JoinEnrichHost = Table.NestedJoin(
				        ExpandMachine, {"m.computerDnsName"},
				        Table.SelectRows(Enrich, each [matchType] = "hostname"), {"matchKey"},
				        "enrich_host", JoinKind.LeftOuter
				    ),
				    ExpandEnrichHost = Table.ExpandTableColumn(JoinEnrichHost, "enrich_host", {
				        "deviceType", "assetCriticality", "dataType", "location", "notes"
				    }, {
				        "eh.deviceType", "eh.assetCriticality", "eh.dataType", "eh.location", "eh.notes"
				    }),
				
				    //        RBAC group match (fallback)
				    JoinEnrichGroup = Table.NestedJoin(
				        ExpandEnrichHost, {"m.rbacGroupName"},
				        Table.SelectRows(Enrich, each [matchType] = "rbacGroup"), {"matchKey"},
				        "enrich_grp", JoinKind.LeftOuter
				    ),
				    ExpandEnrichGroup = Table.ExpandTableColumn(JoinEnrichGroup, "enrich_grp", {
				        "deviceType", "assetCriticality", "dataType", "location", "notes"
				    }, {
				        "eg.deviceType", "eg.assetCriticality", "eg.dataType", "eg.location", "eg.notes"
				    }),
				
				    //        IP match (second fallback)
				    JoinEnrichIP = Table.NestedJoin(
				        ExpandEnrichGroup, {"m.lastIpAddress"},
				        Table.SelectRows(Enrich, each [matchType] = "ipAddress"), {"matchKey"},
				        "enrich_ip", JoinKind.LeftOuter
				    ),
				    ExpandEnrichIP = Table.ExpandTableColumn(JoinEnrichIP, "enrich_ip", {
				        "deviceType", "assetCriticality", "dataType", "location", "notes"
				    }, {
				        "ei.deviceType", "ei.assetCriticality", "ei.dataType", "ei.location", "ei.notes"
				    }),
				
				    // ── 4.  Add row index for Unique ID (column A) ─────────────────────
				    Indexed = Table.AddIndexColumn(ExpandEnrichIP, "RowNum", 1, 1, Int64.Type),
				
				    // ── 5.  Compute derived columns ────────────────────────────────────
				
				    // --- Column A: Unique ID ---
				    AddUniqueId = Table.AddColumn(Indexed, "A_UniqueId",
				        each Text.From([RowNum]), type text),
				
				    // --- Column B: Criticality ---
				    //     If publicExploit or exploitVerified → "Exploitable"
				    //     else map severity string
				    AddCriticality = Table.AddColumn(AddUniqueId, "B_Criticality", each
				        if [v.publicExploit] = true or [v.exploitVerified] = true then "Exploitable"
				        else if [v.severity] = "Critical" then "Critical"
				        else if [v.severity] = "High"     then "High"
				        else if [v.severity] = "Medium"   then "Medium"
				        else "Low",
				        type text),
				
				    // --- Column C: CVE / CVSS ---
				    AddCveId = Table.AddColumn(AddCriticality, "C_CveId",
				        each [cveId], type text),
				    AddCvss  = Table.AddColumn(AddCveId, "C_CvssScore",
				        each [v.cvssV3], type number),
				
				    // --- Column D: Description ---
				    AddDesc = Table.AddColumn(AddCvss, "D_Description",
				        each [v.description], type text),
				
				    // --- Column E: Device OS  (normalise the API's osPlatform string) ---
				    AddOS = Table.AddColumn(AddDesc, "E_DeviceOS", each
				        let p = Text.Lower([m.osPlatform] ?? "") in
				        if Text.Contains(p, "windows11")         then "Windows 11"
				        else if Text.Contains(p, "windows10")    then "Windows 10"
				        else if Text.Contains(p, "windowsserver2022") then "Windows Server 2022"
				        else if Text.Contains(p, "windowsserver2019") or Text.Contains(p, "windows_server_2019") then "Windows Server 2019"
				        else if Text.Contains(p, "windowsserver2016") or Text.Contains(p, "windows_server_2016") then "Windows Server 2016"
				        else if Text.Contains(p, "windows_server_2012") then "Windows Server 2012 R2"
				        else if Text.Contains(p, "linux")   then "Linux"
				        else if Text.Contains(p, "macos")   then "macOS"
				        else if Text.Contains(p, "ios")     then "iOS"
				        else if Text.Contains(p, "android") then "Android"
				        else ([m.osPlatform] ?? "Unknown"),
				        type text),
				
				    // --- Column F: Device Type  (enrichment → default) ---
				    AddDeviceType = Table.AddColumn(AddOS, "F_DeviceType", each
				        [eh.deviceType] ?? [eg.deviceType] ?? [ei.deviceType]
				            ?? Defaults[DeviceType],
				        type text),
				
				    // --- Column G: Date First Detected ---
				    AddFirstDetected = Table.AddColumn(AddDeviceType, "G_DateFirstDetected", each
				        [v.firstDetected] ?? [v.publishedOn],
				        type datetime),
				
				    // --- Column H: Date Last Detected ---
				    AddLastDetected = Table.AddColumn(AddFirstDetected, "H_DateLastDetected", each
				        [v.updatedOn],
				        type datetime),
				
				    // --- Column I: Status  (aging bucket from first-detected) ---
				    AddStatus = Table.AddColumn(AddLastDetected, "I_Status", each
				        if [v.status] = "NoActionRequired" then "Patched"
				        else
				            let
				                first = [v.firstDetected] ?? [v.publishedOn],
				                days  = if first <> null
				                        then Duration.TotalDays(DateTime.LocalNow() - first)
				                        else 0
				            in
				                if days > 90 then "Pending > 3 months"
				                else if days > 60 then "Pending > 2 months"
				                else if days > 30 then "Pending > 1 month"
				                else "Pending < 1 month",
				        type text),
				
				    // --- Column J: Risk Acceptance ---
				    AddRisk = Table.AddColumn(AddStatus, "J_RiskAcceptance", each
				        if [v.status] = "UnderException" or [v.status] = "PartialException"
				        then "Yes" else "No",
				        type text),
				
				    // --- Column K: Asset Criticality ---
				    AddAssetCrit = Table.AddColumn(AddRisk, "K_AssetCriticality", each
				        [eh.assetCriticality] ?? [eg.assetCriticality] ?? [ei.assetCriticality]
				            ?? Defaults[AssetCriticality],
				        type text),
				
				    // --- Column L: Data Type ---
				    AddDataType = Table.AddColumn(AddAssetCrit, "L_DataType", each
				        [eh.dataType] ?? [eg.dataType] ?? [ei.dataType]
				            ?? Defaults[DataType],
				        type text),
				
				    // --- Column M: Location ---
				    AddLocation = Table.AddColumn(AddDataType, "M_Location", each
				        [eh.location] ?? [eg.location] ?? [ei.location]
				            ?? Defaults[Location],
				        type text),
				
				    // --- Column N: Notes ---
				    AddNotes = Table.AddColumn(AddLocation, "N_Notes", each
				        [eh.notes] ?? [eg.notes] ?? [ei.notes] ?? "",
				        type text),
				
				    // --- Column O: Product (bonus context from Defender) ---
				    AddProduct = Table.AddColumn(AddNotes, "O_Product", each
				        [productName] ?? "",
				        type text),
				
				    // --- Column P: Machine Name (hostname from Defender) ---
				    AddMachineName = Table.AddColumn(AddProduct, "P_MachineName", each
				        [m.computerDnsName] ?? "", type text),
				
				    // ── 6.  Select only the final report columns ───────────────────────
				    FinalColumns = Table.SelectColumns(AddMachineName, {
				        "A_UniqueId", "B_Criticality", "C_CveId", "C_CvssScore",
				        "D_Description", "E_DeviceOS", "F_DeviceType",
				        "G_DateFirstDetected", "H_DateLastDetected",
				        "I_Status", "J_RiskAcceptance",
				        "K_AssetCriticality", "L_DataType", "M_Location",
				        "N_Notes", "O_Product", "P_MachineName"
				    }),
				
				    // Friendly column names for the report
				    Renamed = Table.RenameColumns(FinalColumns, {
				        {"A_UniqueId",          "Unique ID"},
				        {"B_Criticality",       "Criticality"},
				        {"C_CveId",             "CVE#"},
				        {"C_CvssScore",         "CVSS Score"},
				        {"D_Description",       "Description"},
				        {"E_DeviceOS",          "Device OS"},
				        {"F_DeviceType",        "Device Type"},
				        {"G_DateFirstDetected", "Date First Detected"},
				        {"H_DateLastDetected",  "Date Last Detected"},
				        {"I_Status",            "Status"},
				        {"J_RiskAcceptance",    "Risk Acceptance"},
				        {"K_AssetCriticality",  "Asset Criticality"},
				        {"L_DataType",          "Data Type"},
				        {"M_Location",          "Location"},
				        {"N_Notes",             "Notes"},
				        {"O_Product",           "Product"},
				        {"P_MachineName",       "Machine Name"}
				    })
				in
				    Renamed

