{
    "compatibilityLevel":  1567,
    "model":  {
                  "culture":  "en-US",
                  "dataAccessOptions":  {
                                            "legacyRedirects":  true,
                                            "returnErrorValuesAsNull":  true
                                        },
                  "defaultPowerBIDataSourceVersion":  "powerBI_V3",
                  "sourceQueryCulture":  "en-US",
                  "expressions":  [
                                      {
                                          "name":  "DefenderApiBaseUrl",
                                          "kind":  "m",
                                          "expression":  "\"https://api.securitycenter.microsoft.com\" meta [IsParameterQuery=true, Type=\"Text\", IsParameterQueryRequired=true]"
                                      },
                                      {
                                          "name":  "fn_PaginatedGet",
                                          "kind":  "m",
                                          "expression":  [
                                                             "// ============================================================================",
                                                             "// fn_PaginatedGet  –  Reusable OData pagination helper",
                                                             "// ============================================================================",
                                                             "// Calls the Defender for Endpoint REST API and follows @odata.nextLink until",
                                                             "// all pages are consumed.  Returns a combined list of records.",
                                                             "//",
                                                             "// Parameters:",
                                                             "//   relativePath  – e.g. \"/api/vulnerabilities\"",
                                                             "//",
                                                             "// Prerequisites:",
                                                             "//   • Data source privacy for api.securitycenter.microsoft.com set to",
                                                             "//     Organizational.",
                                                             "//   • Credentials configured as \"Organizational account\" for the base URL.",
                                                             "// ============================================================================",
                                                             "",
                                                             "let",
                                                             "    fn = (relativePath as text) as list =\u003e",
                                                             "        let",
                                                             "            BaseUrl = DefenderApiBaseUrl,",
                                                             "",
                                                             "            // First page uses RelativePath option for credential resolution",
                                                             "            GetFirstPage = () =\u003e",
                                                             "                let",
                                                             "                    Raw  = Web.Contents(BaseUrl, [RelativePath = relativePath, Headers = [Accept = \"application/json\"]]),",
                                                             "                    Json = Json.Document(Raw),",
                                                             "                    Data = Json[value],",
                                                             "                    Next = try Json[#\"@odata.nextLink\"] otherwise null",
                                                             "                in",
                                                             "                    [Data = Data, NextLink = Next],",
                                                             "",
                                                             "            // Subsequent pages follow the full @odata.nextLink URL",
                                                             "            GetNextPage = (url as text) =\u003e",
                                                             "                let",
                                                             "                    Raw  = Web.Contents(url),",
                                                             "                    Json = Json.Document(Raw),",
                                                             "                    Data = Json[value],",
                                                             "                    Next = try Json[#\"@odata.nextLink\"] otherwise null",
                                                             "                in",
                                                             "                    [Data = Data, NextLink = Next],",
                                                             "",
                                                             "            Accumulate = (accum as list, nextUrl as nullable text, isFirst as logical) =\u003e",
                                                             "                let",
                                                             "                    Page   = if isFirst then GetFirstPage() else GetNextPage(nextUrl),",
                                                             "                    Merged = accum \u0026 Page[Data],",
                                                             "                    Result = if Page[NextLink] \u003c\u003e null",
                                                             "                             then @Accumulate(Merged, Page[NextLink], false)",
                                                             "                             else Merged",
                                                             "                in",
                                                             "                    Result,",
                                                             "",
                                                             "            AllRecords = Accumulate({}, null, true)",
                                                             "        in",
                                                             "            AllRecords",
                                                             "in",
                                                             "    fn"
                                                         ]
                                      },
                                      {
                                          "name":  "EnrichmentFilePath",
                                          "kind":  "m",
                                          "expression":  "\"C:\\Users\\CFoulon\\OneDrive - Quisitive\\Apps\\vrm-report\\data\\enrichment\\asset-enrichment.json\" meta [IsParameterQuery=true, Type=\"Text\", IsParameterQueryRequired=true]"
                                      },
                                      {
                                          "name":  "Vulnerabilities",
                                          "kind":  "m",
                                          "expression":  [
                                                             "// ============================================================================",
                                                             "// Vulnerabilities  –  GET /api/vulnerabilities",
                                                             "// ============================================================================",
                                                             "// All known CVEs from Microsoft Defender for Endpoint.",
                                                             "// Feeds columns B (Criticality), C (CVE/CVSS), D (Description), G, H, I, J.",
                                                             "// ============================================================================",
                                                             "",
                                                             "let",
                                                             "    RawList = fn_PaginatedGet(\"/api/vulnerabilities\"),",
                                                             "",
                                                             "    AsTable = Table.FromList(RawList, Splitter.SplitByNothing(), null, null, ExtraValues.Error),",
                                                             "    Expanded = Table.ExpandRecordColumn(",
                                                             "        AsTable, \"Column1\",",
                                                             "        {",
                                                             "            \"id\", \"name\", \"description\", \"severity\",",
                                                             "            \"cvssV3\", \"cvssVector\",",
                                                             "            \"exposedMachines\", \"publishedOn\", \"updatedOn\", \"firstDetected\",",
                                                             "            \"publicExploit\", \"exploitVerified\", \"exploitInKit\",",
                                                             "            \"exploitTypes\", \"exploitUris\",",
                                                             "            \"cveSupportability\", \"tags\", \"epss\",",
                                                             "            \"status\"",
                                                             "        }",
                                                             "    ),",
                                                             "",
                                                             "    // Type the key columns",
                                                             "    Typed = Table.TransformColumnTypes(Expanded, {",
                                                             "        {\"id\",              type text},",
                                                             "        {\"name\",            type text},",
                                                             "        {\"description\",     type text},",
                                                             "        {\"severity\",        type text},",
                                                             "        {\"cvssV3\",          type number},",
                                                             "        {\"exposedMachines\", Int64.Type},",
                                                             "        {\"publishedOn\",     type datetime},",
                                                             "        {\"updatedOn\",       type datetime},",
                                                             "        {\"firstDetected\",   type datetime},",
                                                             "        {\"publicExploit\",   type logical},",
                                                             "        {\"exploitVerified\", type logical},",
                                                             "        {\"exploitInKit\",    type logical},",
                                                             "        {\"epss\",            type number},",
                                                             "        {\"status\",          type text}",
                                                             "    })",
                                                             "in",
                                                             "    Typed"
                                                         ]
                                      },
                                      {
                                          "name":  "MachineVulnerabilities",
                                          "kind":  "m",
                                          "expression":  [
                                                             "// ============================================================================",
                                                             "// MachineVulnerabilities  –  GET /api/vulnerabilities/machinesVulnerabilities",
                                                             "// ============================================================================",
                                                             "// One row per machine × CVE × product.  This is the primary join table for the",
                                                             "// VRM report (links a CVE to a specific device).",
                                                             "// ============================================================================",
                                                             "",
                                                             "let",
                                                             "    RawList = fn_PaginatedGet(\"/api/vulnerabilities/machinesVulnerabilities\"),",
                                                             "",
                                                             "    AsTable = Table.FromList(RawList, Splitter.SplitByNothing(), null, null, ExtraValues.Error),",
                                                             "    Expanded = Table.ExpandRecordColumn(",
                                                             "        AsTable, \"Column1\",",
                                                             "        {",
                                                             "            \"id\", \"cveId\", \"machineId\",",
                                                             "            \"fixingKbId\",",
                                                             "            \"productName\", \"productVendor\", \"productVersion\",",
                                                             "            \"severity\"",
                                                             "        }",
                                                             "    ),",
                                                             "",
                                                             "    Typed = Table.TransformColumnTypes(Expanded, {",
                                                             "        {\"id\",             type text},",
                                                             "        {\"cveId\",          type text},",
                                                             "        {\"machineId\",      type text},",
                                                             "        {\"fixingKbId\",     type text},",
                                                             "        {\"productName\",    type text},",
                                                             "        {\"productVendor\",  type text},",
                                                             "        {\"productVersion\", type text},",
                                                             "        {\"severity\",       type text}",
                                                             "    })",
                                                             "in",
                                                             "    Typed"
                                                         ]
                                      },
                                      {
                                          "name":  "Machines",
                                          "kind":  "m",
                                          "expression":  [
                                                             "// ============================================================================",
                                                             "// Machines  –  GET /api/machines",
                                                             "// ============================================================================",
                                                             "// Machine reference data for Device OS (column E) and hostname lookups.",
                                                             "// Only a subset of fields is kept to reduce memory usage.",
                                                             "// ============================================================================",
                                                             "",
                                                             "let",
                                                             "    RawList = fn_PaginatedGet(\"/api/machines\"),",
                                                             "",
                                                             "    AsTable = Table.FromList(RawList, Splitter.SplitByNothing(), null, null, ExtraValues.Error),",
                                                             "    Expanded = Table.ExpandRecordColumn(",
                                                             "        AsTable, \"Column1\",",
                                                             "        {",
                                                             "            \"id\", \"computerDnsName\", \"osPlatform\",",
                                                             "            \"rbacGroupName\", \"lastIpAddress\",",
                                                             "            \"healthStatus\", \"riskScore\", \"exposureLevel\", \"deviceValue\"",
                                                             "        }",
                                                             "    ),",
                                                             "",
                                                             "    Typed = Table.TransformColumnTypes(Expanded, {",
                                                             "        {\"id\",              type text},",
                                                             "        {\"computerDnsName\", type text},",
                                                             "        {\"osPlatform\",      type text},",
                                                             "        {\"rbacGroupName\",   type text},",
                                                             "        {\"lastIpAddress\",   type text},",
                                                             "        {\"healthStatus\",    type text},",
                                                             "        {\"riskScore\",       type text},",
                                                             "        {\"exposureLevel\",   type text},",
                                                             "        {\"deviceValue\",     type text}",
                                                             "    })",
                                                             "in",
                                                             "    Typed"
                                                         ]
                                      },
                                      {
                                          "name":  "Enrichment",
                                          "kind":  "m",
                                          "expression":  [
                                                             "// ============================================================================",
                                                             "// Enrichment  –  Local JSON business-context data",
                                                             "// ============================================================================",
                                                             "// Loads asset-enrichment.json (same format as the Node.js project) and",
                                                             "// provides columns that Defender for Endpoint does not supply:",
                                                             "//   F – Device Type,  K – Asset Criticality,  L – Data Type,",
                                                             "//   M – Location,     N – Notes",
                                                             "//",
                                                             "// Change the FilePath parameter below to point to your enrichment file.",
                                                             "// ============================================================================",
                                                             "",
                                                             "let",
                                                             "    FilePath = EnrichmentFilePath,",
                                                             "",
                                                             "    RawJson  = Json.Document(File.Contents(FilePath)),",
                                                             "",
                                                             "    // Extract defaults",
                                                             "    Defaults = RawJson[defaults],",
                                                             "    DefaultAssetCriticality = try Defaults[assetCriticality] otherwise \"Moderate Impact\",",
                                                             "    DefaultDataType         = try Defaults[dataType]         otherwise \"End Point User\",",
                                                             "    DefaultLocation         = try Defaults[location]         otherwise \"Internal\",",
                                                             "    DefaultDeviceType       = try Defaults[deviceType]       otherwise \"Desktop\",",
                                                             "",
                                                             "    // Extract asset list → table",
                                                             "    Assets  = RawJson[assets],",
                                                             "    AsTable = Table.FromList(Assets, Splitter.SplitByNothing(), null, null, ExtraValues.Error),",
                                                             "    Expanded = Table.ExpandRecordColumn(",
                                                             "        AsTable, \"Column1\",",
                                                             "        {\"matchKey\", \"matchType\", \"deviceType\", \"assetCriticality\", \"dataType\", \"location\", \"notes\"}",
                                                             "    ),",
                                                             "",
                                                             "    // Replace nulls with defaults",
                                                             "    WithDefaults = Table.ReplaceValue(",
                                                             "        Table.ReplaceValue(",
                                                             "            Table.ReplaceValue(",
                                                             "                Table.ReplaceValue(",
                                                             "                    Expanded,",
                                                             "                    null, DefaultDeviceType,",
                                                             "                    Replacer.ReplaceValue, {\"deviceType\"}",
                                                             "                ),",
                                                             "                null, DefaultAssetCriticality,",
                                                             "                Replacer.ReplaceValue, {\"assetCriticality\"}",
                                                             "            ),",
                                                             "            null, DefaultDataType,",
                                                             "            Replacer.ReplaceValue, {\"dataType\"}",
                                                             "        ),",
                                                             "        null, DefaultLocation,",
                                                             "        Replacer.ReplaceValue, {\"location\"}",
                                                             "    ),",
                                                             "",
                                                             "    // Fill empty notes with blank string",
                                                             "    Final = Table.ReplaceValue(WithDefaults, null, \"\", Replacer.ReplaceValue, {\"notes\"}),",
                                                             "",
                                                             "    // Record of default values so VRM_Report can reference them",
                                                             "    _Defaults = [",
                                                             "        DefaultDeviceType       = DefaultDeviceType,",
                                                             "        DefaultAssetCriticality = DefaultAssetCriticality,",
                                                             "        DefaultDataType         = DefaultDataType,",
                                                             "        DefaultLocation         = DefaultLocation",
                                                             "    ]",
                                                             "in",
                                                             "    Final"
                                                         ]
                                      },
                                      {
                                          "name":  "EnrichmentDefaults",
                                          "kind":  "m",
                                          "expression":  [
                                                             "// ============================================================================",
                                                             "// EnrichmentDefaults  –  Expose defaults from enrichment JSON",
                                                             "// ============================================================================",
                                                             "// Reads the same JSON file as Enrichment and returns a single record",
                                                             "// containing the default values.  Referenced by VRM_Report when no",
                                                             "// enrichment match is found.",
                                                             "// ============================================================================",
                                                             "",
                                                             "let",
                                                             "    FilePath = EnrichmentFilePath,",
                                                             "    RawJson  = Json.Document(File.Contents(FilePath)),",
                                                             "    Defaults = RawJson[defaults],",
                                                             "",
                                                             "    Result = [",
                                                             "        DeviceType       = try Defaults[deviceType]       otherwise \"Desktop\",",
                                                             "        AssetCriticality = try Defaults[assetCriticality] otherwise \"Moderate Impact\",",
                                                             "        DataType         = try Defaults[dataType]         otherwise \"End Point User\",",
                                                             "        Location         = try Defaults[location]         otherwise \"Internal\"",
                                                             "    ]",
                                                             "in",
                                                             "    Result"
                                                         ]
                                      }
                                  ],
                  "tables":  [
                                 {
                                     "name":  "VRM_Report",
                                     "columns":  [
                                                     {
                                                         "name":  "Unique ID",
                                                         "dataType":  "string",
                                                         "sourceColumn":  "Unique ID",
                                                         "summarizeBy":  "none"
                                                     },
                                                     {
                                                         "name":  "Criticality",
                                                         "dataType":  "string",
                                                         "sourceColumn":  "Criticality",
                                                         "summarizeBy":  "none"
                                                     },
                                                     {
                                                         "name":  "CVE#",
                                                         "dataType":  "string",
                                                         "sourceColumn":  "CVE#",
                                                         "summarizeBy":  "none"
                                                     },
                                                     {
                                                         "name":  "CVSS Score",
                                                         "dataType":  "double",
                                                         "sourceColumn":  "CVSS Score",
                                                         "summarizeBy":  "none"
                                                     },
                                                     {
                                                         "name":  "Description",
                                                         "dataType":  "string",
                                                         "sourceColumn":  "Description",
                                                         "summarizeBy":  "none"
                                                     },
                                                     {
                                                         "name":  "Device OS",
                                                         "dataType":  "string",
                                                         "sourceColumn":  "Device OS",
                                                         "summarizeBy":  "none"
                                                     },
                                                     {
                                                         "name":  "Device Type",
                                                         "dataType":  "string",
                                                         "sourceColumn":  "Device Type",
                                                         "summarizeBy":  "none"
                                                     },
                                                     {
                                                         "name":  "Date First Detected",
                                                         "dataType":  "dateTime",
                                                         "sourceColumn":  "Date First Detected",
                                                         "summarizeBy":  "none",
                                                         "formatString":  "General Date"
                                                     },
                                                     {
                                                         "name":  "Date Last Detected",
                                                         "dataType":  "dateTime",
                                                         "sourceColumn":  "Date Last Detected",
                                                         "summarizeBy":  "none",
                                                         "formatString":  "General Date"
                                                     },
                                                     {
                                                         "name":  "Status",
                                                         "dataType":  "string",
                                                         "sourceColumn":  "Status",
                                                         "summarizeBy":  "none"
                                                     },
                                                     {
                                                         "name":  "Risk Acceptance",
                                                         "dataType":  "string",
                                                         "sourceColumn":  "Risk Acceptance",
                                                         "summarizeBy":  "none"
                                                     },
                                                     {
                                                         "name":  "Asset Criticality",
                                                         "dataType":  "string",
                                                         "sourceColumn":  "Asset Criticality",
                                                         "summarizeBy":  "none"
                                                     },
                                                     {
                                                         "name":  "Data Type",
                                                         "dataType":  "string",
                                                         "sourceColumn":  "Data Type",
                                                         "summarizeBy":  "none"
                                                     },
                                                     {
                                                         "name":  "Location",
                                                         "dataType":  "string",
                                                         "sourceColumn":  "Location",
                                                         "summarizeBy":  "none"
                                                     },
                                                     {
                                                         "name":  "Notes",
                                                         "dataType":  "string",
                                                         "sourceColumn":  "Notes",
                                                         "summarizeBy":  "none"
                                                     },
                                                     {
                                                         "name":  "Product",
                                                         "dataType":  "string",
                                                         "sourceColumn":  "Product",
                                                         "summarizeBy":  "none"
                                                     },
                                                     {
                                                         "name":  "Machine Name",
                                                         "dataType":  "string",
                                                         "sourceColumn":  "Machine Name",
                                                         "summarizeBy":  "none"
                                                     }
                                                 ],
                                     "measures":  [
                                                      {
                                                          "name":  "Total Vulnerabilities",
                                                          "expression":  "COUNTROWS(\u0027VRM_Report\u0027)"
                                                      },
                                                      {
                                                          "name":  "Unique CVEs",
                                                          "expression":  "DISTINCTCOUNT(\u0027VRM_Report\u0027[CVE#])"
                                                      },
                                                      {
                                                          "name":  "Unique Machines",
                                                          "expression":  "DISTINCTCOUNT(\u0027VRM_Report\u0027[Machine Name])"
                                                      },
                                                      {
                                                          "name":  "Critical Count",
                                                          "expression":  "CALCULATE(COUNTROWS(\u0027VRM_Report\u0027), \u0027VRM_Report\u0027[Criticality] = \"Critical\")"
                                                      },
                                                      {
                                                          "name":  "High Count",
                                                          "expression":  "CALCULATE(COUNTROWS(\u0027VRM_Report\u0027), \u0027VRM_Report\u0027[Criticality] = \"High\")"
                                                      },
                                                      {
                                                          "name":  "Exploitable Count",
                                                          "expression":  "CALCULATE(COUNTROWS(\u0027VRM_Report\u0027), \u0027VRM_Report\u0027[Criticality] = \"Exploitable\")"
                                                      },
                                                      {
                                                          "name":  "Medium Count",
                                                          "expression":  "CALCULATE(COUNTROWS(\u0027VRM_Report\u0027), \u0027VRM_Report\u0027[Criticality] = \"Medium\")"
                                                      },
                                                      {
                                                          "name":  "Low Count",
                                                          "expression":  "CALCULATE(COUNTROWS(\u0027VRM_Report\u0027), \u0027VRM_Report\u0027[Criticality] = \"Low\")"
                                                      },
                                                      {
                                                          "name":  "Patched Count",
                                                          "expression":  "CALCULATE(COUNTROWS(\u0027VRM_Report\u0027), \u0027VRM_Report\u0027[Status] = \"Patched\")"
                                                      },
                                                      {
                                                          "name":  "Pending Under 1 Month",
                                                          "expression":  "CALCULATE(COUNTROWS(\u0027VRM_Report\u0027), \u0027VRM_Report\u0027[Status] = \"Pending \u003c 1 month\")"
                                                      },
                                                      {
                                                          "name":  "Pending Over 1 Month",
                                                          "expression":  "CALCULATE(COUNTROWS(\u0027VRM_Report\u0027), \u0027VRM_Report\u0027[Status] = \"Pending \u003e 1 month\")"
                                                      },
                                                      {
                                                          "name":  "Pending Over 2 Months",
                                                          "expression":  "CALCULATE(COUNTROWS(\u0027VRM_Report\u0027), \u0027VRM_Report\u0027[Status] = \"Pending \u003e 2 months\")"
                                                      },
                                                      {
                                                          "name":  "Pending Over 3 Months",
                                                          "expression":  "CALCULATE(COUNTROWS(\u0027VRM_Report\u0027), \u0027VRM_Report\u0027[Status] = \"Pending \u003e 3 months\")"
                                                      },
                                                      {
                                                          "name":  "Risk Accepted Count",
                                                          "expression":  "CALCULATE(COUNTROWS(\u0027VRM_Report\u0027), \u0027VRM_Report\u0027[Risk Acceptance] = \"Yes\")"
                                                      },
                                                      {
                                                          "name":  "Risk Accepted Pct",
                                                          "expression":  "DIVIDE([Risk Accepted Count], [Total Vulnerabilities], 0)"
                                                      },
                                                      {
                                                          "name":  "Average CVSS",
                                                          "expression":  "AVERAGE(\u0027VRM_Report\u0027[CVSS Score])"
                                                      },
                                                      {
                                                          "name":  "Critical or Exploitable Unpatched",
                                                          "expression":  "CALCULATE(\r\n    COUNTROWS(\u0027VRM_Report\u0027),\r\n    \u0027VRM_Report\u0027[Criticality] IN {\"Critical\", \"Exploitable\"},\r\n    \u0027VRM_Report\u0027[Status] \u003c\u003e \"Patched\"\r\n)"
                                                      },
                                                      {
                                                          "name":  "Overdue Over 90 Days",
                                                          "expression":  "CALCULATE(COUNTROWS(\u0027VRM_Report\u0027), \u0027VRM_Report\u0027[Status] = \"Pending \u003e 3 months\")"
                                                      },
                                                      {
                                                          "name":  "Avg Days Open",
                                                          "expression":  "AVERAGEX(\r\n    FILTER(\u0027VRM_Report\u0027, \u0027VRM_Report\u0027[Status] \u003c\u003e \"Patched\"),\r\n    DATEDIFF(\u0027VRM_Report\u0027[Date First Detected], TODAY(), DAY)\r\n)"
                                                      }
                                                  ],
                                     "partitions":  [
                                                        {
                                                            "name":  "VRM_Report-partition",
                                                            "mode":  "import",
                                                            "source":  {
                                                                           "type":  "m",
                                                                           "expression":  [
                                                                                              "// ============================================================================",
                                                                                              "// VRM_Report  –  Final report table  (columns A – O)",
                                                                                              "// ============================================================================",
                                                                                              "// Joins MachineVulnerabilities × Vulnerabilities × Machines × Enrichment and",
                                                                                              "// computes every derived column exactly as the TypeScript mapper does.",
                                                                                              "//",
                                                                                              "// Depends on queries:",
                                                                                              "//   MachineVulnerabilities, Vulnerabilities, Machines,",
                                                                                              "//   Enrichment, EnrichmentDefaults, fn_PaginatedGet",
                                                                                              "// ============================================================================",
                                                                                              "",
                                                                                              "let",
                                                                                              "    // ── 0.  Load source queries ─────────────────────────────────────────",
                                                                                              "    MV       = MachineVulnerabilities,",
                                                                                              "    Vulns    = Vulnerabilities,",
                                                                                              "    Machines = Machines,",
                                                                                              "    Enrich   = Enrichment,",
                                                                                              "    Defaults = EnrichmentDefaults,",
                                                                                              "",
                                                                                              "    // ── 1.  Join MachineVulnerabilities → Vulnerabilities on cveId ──────",
                                                                                              "    JoinVuln = Table.NestedJoin(",
                                                                                              "        MV, {\"cveId\"}, Vulns, {\"id\"}, \"vuln\", JoinKind.Inner",
                                                                                              "    ),",
                                                                                              "    ExpandVuln = Table.ExpandTableColumn(JoinVuln, \"vuln\", {",
                                                                                              "        \"description\", \"severity\", \"cvssV3\", \"publishedOn\", \"updatedOn\",",
                                                                                              "        \"firstDetected\", \"publicExploit\", \"exploitVerified\", \"status\"",
                                                                                              "    }, {",
                                                                                              "        \"v.description\", \"v.severity\", \"v.cvssV3\", \"v.publishedOn\",",
                                                                                              "        \"v.updatedOn\", \"v.firstDetected\", \"v.publicExploit\",",
                                                                                              "        \"v.exploitVerified\", \"v.status\"",
                                                                                              "    }),",
                                                                                              "",
                                                                                              "    // ── 2.  Join → Machines on machineId for OS / hostname ─────────────",
                                                                                              "    JoinMachine = Table.NestedJoin(",
                                                                                              "        ExpandVuln, {\"machineId\"}, Machines, {\"id\"}, \"machine\", JoinKind.LeftOuter",
                                                                                              "    ),",
                                                                                              "    ExpandMachine = Table.ExpandTableColumn(JoinMachine, \"machine\", {",
                                                                                              "        \"computerDnsName\", \"osPlatform\", \"rbacGroupName\", \"lastIpAddress\"",
                                                                                              "    }, {",
                                                                                              "        \"m.computerDnsName\", \"m.osPlatform\", \"m.rbacGroupName\", \"m.lastIpAddress\"",
                                                                                              "    }),",
                                                                                              "",
                                                                                              "    // ── 3.  Join → Enrichment  (try hostname, then rbacGroup) ──────────",
                                                                                              "    //        Hostname match",
                                                                                              "    JoinEnrichHost = Table.NestedJoin(",
                                                                                              "        ExpandMachine, {\"m.computerDnsName\"},",
                                                                                              "        Table.SelectRows(Enrich, each [matchType] = \"hostname\"), {\"matchKey\"},",
                                                                                              "        \"enrich_host\", JoinKind.LeftOuter",
                                                                                              "    ),",
                                                                                              "    ExpandEnrichHost = Table.ExpandTableColumn(JoinEnrichHost, \"enrich_host\", {",
                                                                                              "        \"deviceType\", \"assetCriticality\", \"dataType\", \"location\", \"notes\"",
                                                                                              "    }, {",
                                                                                              "        \"eh.deviceType\", \"eh.assetCriticality\", \"eh.dataType\", \"eh.location\", \"eh.notes\"",
                                                                                              "    }),",
                                                                                              "",
                                                                                              "    //        RBAC group match (fallback)",
                                                                                              "    JoinEnrichGroup = Table.NestedJoin(",
                                                                                              "        ExpandEnrichHost, {\"m.rbacGroupName\"},",
                                                                                              "        Table.SelectRows(Enrich, each [matchType] = \"rbacGroup\"), {\"matchKey\"},",
                                                                                              "        \"enrich_grp\", JoinKind.LeftOuter",
                                                                                              "    ),",
                                                                                              "    ExpandEnrichGroup = Table.ExpandTableColumn(JoinEnrichGroup, \"enrich_grp\", {",
                                                                                              "        \"deviceType\", \"assetCriticality\", \"dataType\", \"location\", \"notes\"",
                                                                                              "    }, {",
                                                                                              "        \"eg.deviceType\", \"eg.assetCriticality\", \"eg.dataType\", \"eg.location\", \"eg.notes\"",
                                                                                              "    }),",
                                                                                              "",
                                                                                              "    //        IP match (second fallback)",
                                                                                              "    JoinEnrichIP = Table.NestedJoin(",
                                                                                              "        ExpandEnrichGroup, {\"m.lastIpAddress\"},",
                                                                                              "        Table.SelectRows(Enrich, each [matchType] = \"ipAddress\"), {\"matchKey\"},",
                                                                                              "        \"enrich_ip\", JoinKind.LeftOuter",
                                                                                              "    ),",
                                                                                              "    ExpandEnrichIP = Table.ExpandTableColumn(JoinEnrichIP, \"enrich_ip\", {",
                                                                                              "        \"deviceType\", \"assetCriticality\", \"dataType\", \"location\", \"notes\"",
                                                                                              "    }, {",
                                                                                              "        \"ei.deviceType\", \"ei.assetCriticality\", \"ei.dataType\", \"ei.location\", \"ei.notes\"",
                                                                                              "    }),",
                                                                                              "",
                                                                                              "    // ── 4.  Add row index for Unique ID (column A) ─────────────────────",
                                                                                              "    Indexed = Table.AddIndexColumn(ExpandEnrichIP, \"RowNum\", 1, 1, Int64.Type),",
                                                                                              "",
                                                                                              "    // ── 5.  Compute derived columns ────────────────────────────────────",
                                                                                              "",
                                                                                              "    // --- Column A: Unique ID ---",
                                                                                              "    AddUniqueId = Table.AddColumn(Indexed, \"A_UniqueId\",",
                                                                                              "        each Text.From([RowNum]), type text),",
                                                                                              "",
                                                                                              "    // --- Column B: Criticality ---",
                                                                                              "    //     If publicExploit or exploitVerified → \"Exploitable\"",
                                                                                              "    //     else map severity string",
                                                                                              "    AddCriticality = Table.AddColumn(AddUniqueId, \"B_Criticality\", each",
                                                                                              "        if [v.publicExploit] = true or [v.exploitVerified] = true then \"Exploitable\"",
                                                                                              "        else if [v.severity] = \"Critical\" then \"Critical\"",
                                                                                              "        else if [v.severity] = \"High\"     then \"High\"",
                                                                                              "        else if [v.severity] = \"Medium\"   then \"Medium\"",
                                                                                              "        else \"Low\",",
                                                                                              "        type text),",
                                                                                              "",
                                                                                              "    // --- Column C: CVE / CVSS ---",
                                                                                              "    AddCveId = Table.AddColumn(AddCriticality, \"C_CveId\",",
                                                                                              "        each [cveId], type text),",
                                                                                              "    AddCvss  = Table.AddColumn(AddCveId, \"C_CvssScore\",",
                                                                                              "        each [v.cvssV3], type number),",
                                                                                              "",
                                                                                              "    // --- Column D: Description ---",
                                                                                              "    AddDesc = Table.AddColumn(AddCvss, \"D_Description\",",
                                                                                              "        each [v.description], type text),",
                                                                                              "",
                                                                                              "    // --- Column E: Device OS  (normalise the API\u0027s osPlatform string) ---",
                                                                                              "    AddOS = Table.AddColumn(AddDesc, \"E_DeviceOS\", each",
                                                                                              "        let p = Text.Lower([m.osPlatform] ?? \"\") in",
                                                                                              "        if Text.Contains(p, \"windows11\")         then \"Windows 11\"",
                                                                                              "        else if Text.Contains(p, \"windows10\")    then \"Windows 10\"",
                                                                                              "        else if Text.Contains(p, \"windowsserver2022\") then \"Windows Server 2022\"",
                                                                                              "        else if Text.Contains(p, \"windowsserver2019\") or Text.Contains(p, \"windows_server_2019\") then \"Windows Server 2019\"",
                                                                                              "        else if Text.Contains(p, \"windowsserver2016\") or Text.Contains(p, \"windows_server_2016\") then \"Windows Server 2016\"",
                                                                                              "        else if Text.Contains(p, \"windows_server_2012\") then \"Windows Server 2012 R2\"",
                                                                                              "        else if Text.Contains(p, \"linux\")   then \"Linux\"",
                                                                                              "        else if Text.Contains(p, \"macos\")   then \"macOS\"",
                                                                                              "        else if Text.Contains(p, \"ios\")     then \"iOS\"",
                                                                                              "        else if Text.Contains(p, \"android\") then \"Android\"",
                                                                                              "        else ([m.osPlatform] ?? \"Unknown\"),",
                                                                                              "        type text),",
                                                                                              "",
                                                                                              "    // --- Column F: Device Type  (enrichment → default) ---",
                                                                                              "    AddDeviceType = Table.AddColumn(AddOS, \"F_DeviceType\", each",
                                                                                              "        [eh.deviceType] ?? [eg.deviceType] ?? [ei.deviceType]",
                                                                                              "            ?? Defaults[DeviceType],",
                                                                                              "        type text),",
                                                                                              "",
                                                                                              "    // --- Column G: Date First Detected ---",
                                                                                              "    AddFirstDetected = Table.AddColumn(AddDeviceType, \"G_DateFirstDetected\", each",
                                                                                              "        [v.firstDetected] ?? [v.publishedOn],",
                                                                                              "        type datetime),",
                                                                                              "",
                                                                                              "    // --- Column H: Date Last Detected ---",
                                                                                              "    AddLastDetected = Table.AddColumn(AddFirstDetected, \"H_DateLastDetected\", each",
                                                                                              "        [v.updatedOn],",
                                                                                              "        type datetime),",
                                                                                              "",
                                                                                              "    // --- Column I: Status  (aging bucket from first-detected) ---",
                                                                                              "    AddStatus = Table.AddColumn(AddLastDetected, \"I_Status\", each",
                                                                                              "        if [v.status] = \"NoActionRequired\" then \"Patched\"",
                                                                                              "        else",
                                                                                              "            let",
                                                                                              "                first = [v.firstDetected] ?? [v.publishedOn],",
                                                                                              "                days  = if first \u003c\u003e null",
                                                                                              "                        then Duration.TotalDays(DateTime.LocalNow() - first)",
                                                                                              "                        else 0",
                                                                                              "            in",
                                                                                              "                if days \u003e 90 then \"Pending \u003e 3 months\"",
                                                                                              "                else if days \u003e 60 then \"Pending \u003e 2 months\"",
                                                                                              "                else if days \u003e 30 then \"Pending \u003e 1 month\"",
                                                                                              "                else \"Pending \u003c 1 month\",",
                                                                                              "        type text),",
                                                                                              "",
                                                                                              "    // --- Column J: Risk Acceptance ---",
                                                                                              "    AddRisk = Table.AddColumn(AddStatus, \"J_RiskAcceptance\", each",
                                                                                              "        if [v.status] = \"UnderException\" or [v.status] = \"PartialException\"",
                                                                                              "        then \"Yes\" else \"No\",",
                                                                                              "        type text),",
                                                                                              "",
                                                                                              "    // --- Column K: Asset Criticality ---",
                                                                                              "    AddAssetCrit = Table.AddColumn(AddRisk, \"K_AssetCriticality\", each",
                                                                                              "        [eh.assetCriticality] ?? [eg.assetCriticality] ?? [ei.assetCriticality]",
                                                                                              "            ?? Defaults[AssetCriticality],",
                                                                                              "        type text),",
                                                                                              "",
                                                                                              "    // --- Column L: Data Type ---",
                                                                                              "    AddDataType = Table.AddColumn(AddAssetCrit, \"L_DataType\", each",
                                                                                              "        [eh.dataType] ?? [eg.dataType] ?? [ei.dataType]",
                                                                                              "            ?? Defaults[DataType],",
                                                                                              "        type text),",
                                                                                              "",
                                                                                              "    // --- Column M: Location ---",
                                                                                              "    AddLocation = Table.AddColumn(AddDataType, \"M_Location\", each",
                                                                                              "        [eh.location] ?? [eg.location] ?? [ei.location]",
                                                                                              "            ?? Defaults[Location],",
                                                                                              "        type text),",
                                                                                              "",
                                                                                              "    // --- Column N: Notes ---",
                                                                                              "    AddNotes = Table.AddColumn(AddLocation, \"N_Notes\", each",
                                                                                              "        [eh.notes] ?? [eg.notes] ?? [ei.notes] ?? \"\",",
                                                                                              "        type text),",
                                                                                              "",
                                                                                              "    // --- Column O: Product (bonus context from Defender) ---",
                                                                                              "    AddProduct = Table.AddColumn(AddNotes, \"O_Product\", each",
                                                                                              "        [productName] ?? \"\",",
                                                                                              "        type text),",
                                                                                              "",
                                                                                              "    // --- Column P: Machine Name (hostname from Defender) ---",
                                                                                              "    AddMachineName = Table.AddColumn(AddProduct, \"P_MachineName\", each",
                                                                                              "        [m.computerDnsName] ?? \"\", type text),",
                                                                                              "",
                                                                                              "    // ── 6.  Select only the final report columns ───────────────────────",
                                                                                              "    FinalColumns = Table.SelectColumns(AddMachineName, {",
                                                                                              "        \"A_UniqueId\", \"B_Criticality\", \"C_CveId\", \"C_CvssScore\",",
                                                                                              "        \"D_Description\", \"E_DeviceOS\", \"F_DeviceType\",",
                                                                                              "        \"G_DateFirstDetected\", \"H_DateLastDetected\",",
                                                                                              "        \"I_Status\", \"J_RiskAcceptance\",",
                                                                                              "        \"K_AssetCriticality\", \"L_DataType\", \"M_Location\",",
                                                                                              "        \"N_Notes\", \"O_Product\", \"P_MachineName\"",
                                                                                              "    }),",
                                                                                              "",
                                                                                              "    // Friendly column names for the report",
                                                                                              "    Renamed = Table.RenameColumns(FinalColumns, {",
                                                                                              "        {\"A_UniqueId\",          \"Unique ID\"},",
                                                                                              "        {\"B_Criticality\",       \"Criticality\"},",
                                                                                              "        {\"C_CveId\",             \"CVE#\"},",
                                                                                              "        {\"C_CvssScore\",         \"CVSS Score\"},",
                                                                                              "        {\"D_Description\",       \"Description\"},",
                                                                                              "        {\"E_DeviceOS\",          \"Device OS\"},",
                                                                                              "        {\"F_DeviceType\",        \"Device Type\"},",
                                                                                              "        {\"G_DateFirstDetected\", \"Date First Detected\"},",
                                                                                              "        {\"H_DateLastDetected\",  \"Date Last Detected\"},",
                                                                                              "        {\"I_Status\",            \"Status\"},",
                                                                                              "        {\"J_RiskAcceptance\",    \"Risk Acceptance\"},",
                                                                                              "        {\"K_AssetCriticality\",  \"Asset Criticality\"},",
                                                                                              "        {\"L_DataType\",          \"Data Type\"},",
                                                                                              "        {\"M_Location\",          \"Location\"},",
                                                                                              "        {\"N_Notes\",             \"Notes\"},",
                                                                                              "        {\"O_Product\",           \"Product\"},",
                                                                                              "        {\"P_MachineName\",       \"Machine Name\"}",
                                                                                              "    })",
                                                                                              "in",
                                                                                              "    Renamed"
                                                                                          ]
                                                                       }
                                                        }
                                                    ]
                                 }
                             ]
              }
}
