{
    "compatibilityLevel":  1567,
    "model":  {
                  "culture":  "en-US",
                  "dataAccessOptions":  {
                                            "legacyRedirects":  true,
                                            "returnErrorValuesAsNull":  true
                                        },
                  "defaultPowerBIDataSourceVersion":  "powerBI_V3",
                  "sourceQueryCulture":  "en-US",
                  "expressions":  [
                                      {
                                          "name":  "CsvFolderPath",
                                          "kind":  "m",
                                          "expression":  "\"C:\\exports\\defender\" meta [IsParameterQuery=true, Type=\"Text\", IsParameterQueryRequired=true]"
                                      },
                                      {
                                          "name":  "EnrichmentFilePath",
                                          "kind":  "m",
                                          "expression":  "\"C:\\Users\\CFoulon\\OneDrive - Quisitive\\Apps\\vrm-report\\data\\enrichment\\asset-enrichment.json\" meta [IsParameterQuery=true, Type=\"Text\", IsParameterQueryRequired=true]"
                                      },
                                      {
                                          "name":  "Vulnerabilities",
                                          "kind":  "m",
                                          "expression":  [
                                                             "// ============================================================================",
                                                             "// Vulnerabilities (CSV)  –  Defender portal Weaknesses export",
                                                             "// ============================================================================",
                                                             "// File: export-tvm-vulnerabilities.csv",
                                                             "// Export from: Security \u003e Vulnerability Management \u003e Weaknesses \u003e Export",
                                                             "//",
                                                             "// Row 1 is a title line (\"Vulnerabilities Export,...\") – skipped.",
                                                             "// Row 2 contains the actual column headers.",
                                                             "//",
                                                             "// Headers: Name, Severity, CVSS v3, Epss score, Age (days), Published,",
                                                             "//          First detected, Updated, Has Exploit, Has Known Threats,",
                                                             "//          Has Associated Alerts, Related Software, Exposed Machines,",
                                                             "//          Description, Status",
                                                             "// ============================================================================",
                                                             "",
                                                             "let",
                                                             "    Source = Csv.Document(",
                                                             "        File.Contents(CsvFolderPath \u0026 \"\\export-tvm-vulnerabilities.csv\"),",
                                                             "        [Delimiter = \",\", Columns = 15, Encoding = 65001, QuoteStyle = QuoteStyle.Csv]",
                                                             "    ),",
                                                             "",
                                                             "    // Skip the title row, promote row 2 as headers",
                                                             "    SkipTitle = Table.Skip(Source, 1),",
                                                             "    Promoted  = Table.PromoteHeaders(SkipTitle, [PromoteAllScalars = true]),",
                                                             "",
                                                             "    // Parse dates: portal uses \"05 Mar, 2026\" format – strip comma first",
                                                             "    CleanDates = Table.TransformColumns(Promoted, {",
                                                             "        {\"Published\",      each Text.Replace(_ ?? \"\", \",\", \"\"), type text},",
                                                             "        {\"First detected\", each Text.Replace(_ ?? \"\", \",\", \"\"), type text},",
                                                             "        {\"Updated\",        each Text.Replace(_ ?? \"\", \",\", \"\"), type text}",
                                                             "    }),",
                                                             "",
                                                             "    Typed = Table.TransformColumnTypes(CleanDates, {",
                                                             "        {\"Name\",                  type text},",
                                                             "        {\"Severity\",              type text},",
                                                             "        {\"CVSS v3\",               type number},",
                                                             "        {\"Epss score\",            type number},",
                                                             "        {\"Age (days)\",            Int64.Type},",
                                                             "        {\"Published\",             type date},",
                                                             "        {\"First detected\",        type date},",
                                                             "        {\"Updated\",               type date},",
                                                             "        {\"Has Exploit\",           type text},",
                                                             "        {\"Has Known Threats\",     type text},",
                                                             "        {\"Has Associated Alerts\", type text},",
                                                             "        {\"Related Software\",      type text},",
                                                             "        {\"Exposed Machines\",      Int64.Type},",
                                                             "        {\"Description\",           type text},",
                                                             "        {\"Status\",                type text}",
                                                             "    })",
                                                             "in",
                                                             "    Typed"
                                                         ]
                                      },
                                      {
                                          "name":  "Machines",
                                          "kind":  "m",
                                          "expression":  [
                                                             "// ============================================================================",
                                                             "// Machines (CSV)  –  Defender portal Devices export",
                                                             "// ============================================================================",
                                                             "// File: devices.csv",
                                                             "// Export from: Assets \u003e Devices \u003e Export",
                                                             "//",
                                                             "// Headers include: Device ID, Device Name, Device Type, OS Platform,",
                                                             "//                  Group, Device IPs, Risk Level, Exposure Level, etc.",
                                                             "// ============================================================================",
                                                             "",
                                                             "let",
                                                             "    Source = Csv.Document(",
                                                             "        File.Contents(CsvFolderPath \u0026 \"\\devices.csv\"),",
                                                             "        [Delimiter = \",\", Encoding = 65001, QuoteStyle = QuoteStyle.Csv]",
                                                             "    ),",
                                                             "    Promoted = Table.PromoteHeaders(Source, [PromoteAllScalars = true]),",
                                                             "",
                                                             "    // Rename to match the column names the API-mode Machines query uses,",
                                                             "    // so VRM_Report can reference them consistently",
                                                             "    Renamed = Table.RenameColumns(Promoted, {",
                                                             "        {\"Device ID\",    \"id\"},",
                                                             "        {\"Device Name\",  \"computerDnsName\"},",
                                                             "        {\"OS Platform\",  \"osPlatform\"},",
                                                             "        {\"Group\",        \"rbacGroupName\"},",
                                                             "        {\"Device IPs\",   \"lastIpAddress\"},",
                                                             "        {\"Health Status\", \"healthStatus\"},",
                                                             "        {\"Risk Level\",   \"riskScore\"},",
                                                             "        {\"Exposure Level\", \"exposureLevel\"},",
                                                             "        {\"Device Type\",  \"portalDeviceType\"}",
                                                             "    }, MissingField.Ignore),",
                                                             "",
                                                             "    // Take only the first IP from the comma-separated list",
                                                             "    CleanIP = Table.TransformColumns(Renamed, {",
                                                             "        {\"lastIpAddress\", each Text.Trim(Text.BeforeDelimiter(_ ?? \"\", \",\")), type text}",
                                                             "    }),",
                                                             "",
                                                             "    Typed = Table.TransformColumnTypes(CleanIP, {",
                                                             "        {\"id\",               type text},",
                                                             "        {\"computerDnsName\",  type text},",
                                                             "        {\"osPlatform\",       type text},",
                                                             "        {\"rbacGroupName\",    type text},",
                                                             "        {\"lastIpAddress\",    type text},",
                                                             "        {\"healthStatus\",     type text},",
                                                             "        {\"riskScore\",        type text},",
                                                             "        {\"exposureLevel\",    type text},",
                                                             "        {\"portalDeviceType\", type text}",
                                                             "    }, MissingField.Ignore)",
                                                             "in",
                                                             "    Typed"
                                                         ]
                                      },
                                      {
                                          "name":  "Enrichment",
                                          "kind":  "m",
                                          "expression":  [
                                                             "// ============================================================================",
                                                             "// Enrichment  –  Local JSON business-context data",
                                                             "// ============================================================================",
                                                             "// Loads asset-enrichment.json (same format as the Node.js project) and",
                                                             "// provides columns that Defender for Endpoint does not supply:",
                                                             "//   F – Device Type,  K – Asset Criticality,  L – Data Type,",
                                                             "//   M – Location,     N – Notes",
                                                             "//",
                                                             "// Change the FilePath parameter below to point to your enrichment file.",
                                                             "// ============================================================================",
                                                             "",
                                                             "let",
                                                             "    FilePath = EnrichmentFilePath,",
                                                             "",
                                                             "    RawJson  = Json.Document(File.Contents(FilePath)),",
                                                             "",
                                                             "    // Extract defaults",
                                                             "    Defaults = RawJson[defaults],",
                                                             "    DefaultAssetCriticality = try Defaults[assetCriticality] otherwise \"Moderate Impact\",",
                                                             "    DefaultDataType         = try Defaults[dataType]         otherwise \"End Point User\",",
                                                             "    DefaultLocation         = try Defaults[location]         otherwise \"Internal\",",
                                                             "    DefaultDeviceType       = try Defaults[deviceType]       otherwise \"Desktop\",",
                                                             "",
                                                             "    // Extract asset list → table",
                                                             "    Assets  = RawJson[assets],",
                                                             "    AsTable = Table.FromList(Assets, Splitter.SplitByNothing(), null, null, ExtraValues.Error),",
                                                             "    Expanded = Table.ExpandRecordColumn(",
                                                             "        AsTable, \"Column1\",",
                                                             "        {\"matchKey\", \"matchType\", \"deviceType\", \"assetCriticality\", \"dataType\", \"location\", \"notes\"}",
                                                             "    ),",
                                                             "",
                                                             "    // Replace nulls with defaults",
                                                             "    WithDefaults = Table.ReplaceValue(",
                                                             "        Table.ReplaceValue(",
                                                             "            Table.ReplaceValue(",
                                                             "                Table.ReplaceValue(",
                                                             "                    Expanded,",
                                                             "                    null, DefaultDeviceType,",
                                                             "                    Replacer.ReplaceValue, {\"deviceType\"}",
                                                             "                ),",
                                                             "                null, DefaultAssetCriticality,",
                                                             "                Replacer.ReplaceValue, {\"assetCriticality\"}",
                                                             "            ),",
                                                             "            null, DefaultDataType,",
                                                             "            Replacer.ReplaceValue, {\"dataType\"}",
                                                             "        ),",
                                                             "        null, DefaultLocation,",
                                                             "        Replacer.ReplaceValue, {\"location\"}",
                                                             "    ),",
                                                             "",
                                                             "    // Fill empty notes with blank string",
                                                             "    Final = Table.ReplaceValue(WithDefaults, null, \"\", Replacer.ReplaceValue, {\"notes\"}),",
                                                             "",
                                                             "    // Record of default values so VRM_Report can reference them",
                                                             "    _Defaults = [",
                                                             "        DefaultDeviceType       = DefaultDeviceType,",
                                                             "        DefaultAssetCriticality = DefaultAssetCriticality,",
                                                             "        DefaultDataType         = DefaultDataType,",
                                                             "        DefaultLocation         = DefaultLocation",
                                                             "    ]",
                                                             "in",
                                                             "    Final"
                                                         ]
                                      },
                                      {
                                          "name":  "EnrichmentDefaults",
                                          "kind":  "m",
                                          "expression":  [
                                                             "// ============================================================================",
                                                             "// EnrichmentDefaults  –  Expose defaults from enrichment JSON",
                                                             "// ============================================================================",
                                                             "// Reads the same JSON file as Enrichment and returns a single record",
                                                             "// containing the default values.  Referenced by VRM_Report when no",
                                                             "// enrichment match is found.",
                                                             "// ============================================================================",
                                                             "",
                                                             "let",
                                                             "    FilePath = EnrichmentFilePath,",
                                                             "    RawJson  = Json.Document(File.Contents(FilePath)),",
                                                             "    Defaults = RawJson[defaults],",
                                                             "",
                                                             "    Result = [",
                                                             "        DeviceType       = try Defaults[deviceType]       otherwise \"Desktop\",",
                                                             "        AssetCriticality = try Defaults[assetCriticality] otherwise \"Moderate Impact\",",
                                                             "        DataType         = try Defaults[dataType]         otherwise \"End Point User\",",
                                                             "        Location         = try Defaults[location]         otherwise \"Internal\"",
                                                             "    ]",
                                                             "in",
                                                             "    Result"
                                                         ]
                                      }
                                  ],
                  "tables":  [
                                 {
                                     "name":  "VRM_Report",
                                     "columns":  [
                                                     {
                                                         "name":  "Unique ID",
                                                         "dataType":  "string",
                                                         "sourceColumn":  "Unique ID",
                                                         "summarizeBy":  "none"
                                                     },
                                                     {
                                                         "name":  "Criticality",
                                                         "dataType":  "string",
                                                         "sourceColumn":  "Criticality",
                                                         "summarizeBy":  "none"
                                                     },
                                                     {
                                                         "name":  "CVE#",
                                                         "dataType":  "string",
                                                         "sourceColumn":  "CVE#",
                                                         "summarizeBy":  "none"
                                                     },
                                                     {
                                                         "name":  "CVSS Score",
                                                         "dataType":  "double",
                                                         "sourceColumn":  "CVSS Score",
                                                         "summarizeBy":  "none"
                                                     },
                                                     {
                                                         "name":  "Description",
                                                         "dataType":  "string",
                                                         "sourceColumn":  "Description",
                                                         "summarizeBy":  "none"
                                                     },
                                                     {
                                                         "name":  "Device OS",
                                                         "dataType":  "string",
                                                         "sourceColumn":  "Device OS",
                                                         "summarizeBy":  "none"
                                                     },
                                                     {
                                                         "name":  "Device Type",
                                                         "dataType":  "string",
                                                         "sourceColumn":  "Device Type",
                                                         "summarizeBy":  "none"
                                                     },
                                                     {
                                                         "name":  "Date First Detected",
                                                         "dataType":  "dateTime",
                                                         "sourceColumn":  "Date First Detected",
                                                         "summarizeBy":  "none",
                                                         "formatString":  "General Date"
                                                     },
                                                     {
                                                         "name":  "Date Last Detected",
                                                         "dataType":  "dateTime",
                                                         "sourceColumn":  "Date Last Detected",
                                                         "summarizeBy":  "none",
                                                         "formatString":  "General Date"
                                                     },
                                                     {
                                                         "name":  "Status",
                                                         "dataType":  "string",
                                                         "sourceColumn":  "Status",
                                                         "summarizeBy":  "none"
                                                     },
                                                     {
                                                         "name":  "Risk Acceptance",
                                                         "dataType":  "string",
                                                         "sourceColumn":  "Risk Acceptance",
                                                         "summarizeBy":  "none"
                                                     },
                                                     {
                                                         "name":  "Asset Criticality",
                                                         "dataType":  "string",
                                                         "sourceColumn":  "Asset Criticality",
                                                         "summarizeBy":  "none"
                                                     },
                                                     {
                                                         "name":  "Data Type",
                                                         "dataType":  "string",
                                                         "sourceColumn":  "Data Type",
                                                         "summarizeBy":  "none"
                                                     },
                                                     {
                                                         "name":  "Location",
                                                         "dataType":  "string",
                                                         "sourceColumn":  "Location",
                                                         "summarizeBy":  "none"
                                                     },
                                                     {
                                                         "name":  "Notes",
                                                         "dataType":  "string",
                                                         "sourceColumn":  "Notes",
                                                         "summarizeBy":  "none"
                                                     },
                                                     {
                                                         "name":  "Product",
                                                         "dataType":  "string",
                                                         "sourceColumn":  "Product",
                                                         "summarizeBy":  "none"
                                                     },
                                                     {
                                                         "name":  "Machine Name",
                                                         "dataType":  "string",
                                                         "sourceColumn":  "Machine Name",
                                                         "summarizeBy":  "none"
                                                     }
                                                 ],
                                     "measures":  [
                                                      {
                                                          "name":  "Total Vulnerabilities",
                                                          "expression":  "COUNTROWS(\u0027VRM_Report\u0027)"
                                                      },
                                                      {
                                                          "name":  "Unique CVEs",
                                                          "expression":  "DISTINCTCOUNT(\u0027VRM_Report\u0027[CVE#])"
                                                      },
                                                      {
                                                          "name":  "Unique Machines",
                                                          "expression":  "DISTINCTCOUNT(\u0027VRM_Report\u0027[Machine Name])"
                                                      },
                                                      {
                                                          "name":  "Critical Count",
                                                          "expression":  "CALCULATE(COUNTROWS(\u0027VRM_Report\u0027), \u0027VRM_Report\u0027[Criticality] = \"Critical\")"
                                                      },
                                                      {
                                                          "name":  "High Count",
                                                          "expression":  "CALCULATE(COUNTROWS(\u0027VRM_Report\u0027), \u0027VRM_Report\u0027[Criticality] = \"High\")"
                                                      },
                                                      {
                                                          "name":  "Exploitable Count",
                                                          "expression":  "CALCULATE(COUNTROWS(\u0027VRM_Report\u0027), \u0027VRM_Report\u0027[Criticality] = \"Exploitable\")"
                                                      },
                                                      {
                                                          "name":  "Medium Count",
                                                          "expression":  "CALCULATE(COUNTROWS(\u0027VRM_Report\u0027), \u0027VRM_Report\u0027[Criticality] = \"Medium\")"
                                                      },
                                                      {
                                                          "name":  "Low Count",
                                                          "expression":  "CALCULATE(COUNTROWS(\u0027VRM_Report\u0027), \u0027VRM_Report\u0027[Criticality] = \"Low\")"
                                                      },
                                                      {
                                                          "name":  "Patched Count",
                                                          "expression":  "CALCULATE(COUNTROWS(\u0027VRM_Report\u0027), \u0027VRM_Report\u0027[Status] = \"Patched\")"
                                                      },
                                                      {
                                                          "name":  "Pending Under 1 Month",
                                                          "expression":  "CALCULATE(COUNTROWS(\u0027VRM_Report\u0027), \u0027VRM_Report\u0027[Status] = \"Pending \u003c 1 month\")"
                                                      },
                                                      {
                                                          "name":  "Pending Over 1 Month",
                                                          "expression":  "CALCULATE(COUNTROWS(\u0027VRM_Report\u0027), \u0027VRM_Report\u0027[Status] = \"Pending \u003e 1 month\")"
                                                      },
                                                      {
                                                          "name":  "Pending Over 2 Months",
                                                          "expression":  "CALCULATE(COUNTROWS(\u0027VRM_Report\u0027), \u0027VRM_Report\u0027[Status] = \"Pending \u003e 2 months\")"
                                                      },
                                                      {
                                                          "name":  "Pending Over 3 Months",
                                                          "expression":  "CALCULATE(COUNTROWS(\u0027VRM_Report\u0027), \u0027VRM_Report\u0027[Status] = \"Pending \u003e 3 months\")"
                                                      },
                                                      {
                                                          "name":  "Risk Accepted Count",
                                                          "expression":  "CALCULATE(COUNTROWS(\u0027VRM_Report\u0027), \u0027VRM_Report\u0027[Risk Acceptance] = \"Yes\")"
                                                      },
                                                      {
                                                          "name":  "Risk Accepted Pct",
                                                          "expression":  "DIVIDE([Risk Accepted Count], [Total Vulnerabilities], 0)"
                                                      },
                                                      {
                                                          "name":  "Average CVSS",
                                                          "expression":  "AVERAGE(\u0027VRM_Report\u0027[CVSS Score])"
                                                      },
                                                      {
                                                          "name":  "Critical or Exploitable Unpatched",
                                                          "expression":  "CALCULATE(\r\n    COUNTROWS(\u0027VRM_Report\u0027),\r\n    \u0027VRM_Report\u0027[Criticality] IN {\"Critical\", \"Exploitable\"},\r\n    \u0027VRM_Report\u0027[Status] \u003c\u003e \"Patched\"\r\n)"
                                                      },
                                                      {
                                                          "name":  "Overdue Over 90 Days",
                                                          "expression":  "CALCULATE(COUNTROWS(\u0027VRM_Report\u0027), \u0027VRM_Report\u0027[Status] = \"Pending \u003e 3 months\")"
                                                      },
                                                      {
                                                          "name":  "Avg Days Open",
                                                          "expression":  "AVERAGEX(\r\n    FILTER(\u0027VRM_Report\u0027, \u0027VRM_Report\u0027[Status] \u003c\u003e \"Patched\"),\r\n    DATEDIFF(\u0027VRM_Report\u0027[Date First Detected], TODAY(), DAY)\r\n)"
                                                      }
                                                  ],
                                     "partitions":  [
                                                        {
                                                            "name":  "VRM_Report-partition",
                                                            "mode":  "import",
                                                            "source":  {
                                                                           "type":  "m",
                                                                           "expression":  [
                                                                                              "// ============================================================================",
                                                                                              "// VRM_Report (CSV)  –  Final report table  (columns A – O)",
                                                                                              "// ============================================================================",
                                                                                              "// CSV-mode variant.  The Defender portal Weaknesses export is CVE-level",
                                                                                              "// (one row per vulnerability, not per machine×CVE), so this query produces",
                                                                                              "// one row per CVE.  The Machines_CSV table is loaded as a supplementary",
                                                                                              "// reference for device-fleet statistics but cannot be joined per-row since",
                                                                                              "// the portal export does not include a machine-to-CVE mapping.",
                                                                                              "//",
                                                                                              "// Depends on: Vulnerabilities (CSV override), Enrichment, EnrichmentDefaults",
                                                                                              "// ============================================================================",
                                                                                              "",
                                                                                              "let",
                                                                                              "    // ── 0.  Load source queries ─────────────────────────────────────────",
                                                                                              "    Vulns    = Vulnerabilities,",
                                                                                              "    Defaults = EnrichmentDefaults,",
                                                                                              "",
                                                                                              "    // ── 1.  Add row index for Unique ID ─────────────────────────────────",
                                                                                              "    Indexed = Table.AddIndexColumn(Vulns, \"RowNum\", 1, 1, Int64.Type),",
                                                                                              "",
                                                                                              "    // ── 2.  Compute derived columns (A – O) ────────────────────────────",
                                                                                              "",
                                                                                              "    // --- Column A: Unique ID ---",
                                                                                              "    AddUniqueId = Table.AddColumn(Indexed, \"A_UniqueId\",",
                                                                                              "        each Text.From([RowNum]), type text),",
                                                                                              "",
                                                                                              "    // --- Column B: Criticality ---",
                                                                                              "    AddCriticality = Table.AddColumn(AddUniqueId, \"B_Criticality\", each",
                                                                                              "        if [#\"Has Exploit\"] = \"True\" then \"Exploitable\"",
                                                                                              "        else if [Severity] = \"Critical\" then \"Critical\"",
                                                                                              "        else if [Severity] = \"High\"     then \"High\"",
                                                                                              "        else if [Severity] = \"Medium\"   then \"Medium\"",
                                                                                              "        else \"Low\",",
                                                                                              "        type text),",
                                                                                              "",
                                                                                              "    // --- Column C: CVE# / CVSS ---",
                                                                                              "    AddCveId = Table.AddColumn(AddCriticality, \"C_CveId\",",
                                                                                              "        each [Name], type text),",
                                                                                              "    AddCvss  = Table.AddColumn(AddCveId, \"C_CvssScore\",",
                                                                                              "        each [#\"CVSS v3\"], type number),",
                                                                                              "",
                                                                                              "    // --- Column D: Description ---",
                                                                                              "    AddDesc = Table.AddColumn(AddCvss, \"D_Description\",",
                                                                                              "        each [Description], type text),",
                                                                                              "",
                                                                                              "    // --- Column E: Device OS ---",
                                                                                              "    // Per-device OS is not available in CVE-level export; show exposed count",
                                                                                              "    AddOS = Table.AddColumn(AddDesc, \"E_DeviceOS\", each",
                                                                                              "        let n = try [#\"Exposed Machines\"] otherwise 0 in",
                                                                                              "        if n = 1 then \"1 device\"",
                                                                                              "        else Text.From(n) \u0026 \" devices\",",
                                                                                              "        type text),",
                                                                                              "",
                                                                                              "    // --- Column F: Device Type  (from enrichment defaults) ---",
                                                                                              "    AddDeviceType = Table.AddColumn(AddOS, \"F_DeviceType\", each",
                                                                                              "        Defaults[DeviceType],",
                                                                                              "        type text),",
                                                                                              "",
                                                                                              "    // --- Column G: Date First Detected ---",
                                                                                              "    AddFirstDetected = Table.AddColumn(AddDeviceType, \"G_DateFirstDetected\", each",
                                                                                              "        [#\"First detected\"],",
                                                                                              "        type date),",
                                                                                              "",
                                                                                              "    // --- Column H: Date Last Detected ---",
                                                                                              "    AddLastDetected = Table.AddColumn(AddFirstDetected, \"H_DateLastDetected\", each",
                                                                                              "        [Updated],",
                                                                                              "        type date),",
                                                                                              "",
                                                                                              "    // --- Column I: Status  (aging bucket from Age (days) column) ---",
                                                                                              "    AddStatus = Table.AddColumn(AddLastDetected, \"I_Status\", each",
                                                                                              "        let st = [Status] ?? \"\" in",
                                                                                              "        if st = \"NoActionRequired\" or st = \"Resolved\" then \"Patched\"",
                                                                                              "        else",
                                                                                              "            let days = try [#\"Age (days)\"] otherwise 0 in",
                                                                                              "            if days \u003e 90 then \"Pending \u003e 3 months\"",
                                                                                              "            else if days \u003e 60 then \"Pending \u003e 2 months\"",
                                                                                              "            else if days \u003e 30 then \"Pending \u003e 1 month\"",
                                                                                              "            else \"Pending \u003c 1 month\",",
                                                                                              "        type text),",
                                                                                              "",
                                                                                              "    // --- Column J: Risk Acceptance ---",
                                                                                              "    AddRisk = Table.AddColumn(AddStatus, \"J_RiskAcceptance\", each",
                                                                                              "        let st = [Status] ?? \"\" in",
                                                                                              "        if st = \"Exception\" or st = \"UnderException\" or st = \"PartialException\"",
                                                                                              "        then \"Yes\" else \"No\",",
                                                                                              "        type text),",
                                                                                              "",
                                                                                              "    // --- Column K: Asset Criticality  (enrichment defaults) ---",
                                                                                              "    AddAssetCrit = Table.AddColumn(AddRisk, \"K_AssetCriticality\", each",
                                                                                              "        Defaults[AssetCriticality],",
                                                                                              "        type text),",
                                                                                              "",
                                                                                              "    // --- Column L: Data Type ---",
                                                                                              "    AddDataType = Table.AddColumn(AddAssetCrit, \"L_DataType\", each",
                                                                                              "        Defaults[DataType],",
                                                                                              "        type text),",
                                                                                              "",
                                                                                              "    // --- Column M: Location ---",
                                                                                              "    AddLocation = Table.AddColumn(AddDataType, \"M_Location\", each",
                                                                                              "        Defaults[Location],",
                                                                                              "        type text),",
                                                                                              "",
                                                                                              "    // --- Column N: Notes ---",
                                                                                              "    AddNotes = Table.AddColumn(AddLocation, \"N_Notes\", each",
                                                                                              "        \"\", type text),",
                                                                                              "",
                                                                                              "    // --- Column O: Product ---",
                                                                                              "    AddProduct = Table.AddColumn(AddNotes, \"O_Product\", each",
                                                                                              "        [#\"Related Software\"] ?? \"\",",
                                                                                              "        type text),",
                                                                                              "",
                                                                                              "    // --- Column P: Machine Name (not available in CSV export; left blank) ---",
                                                                                              "    AddMachineName = Table.AddColumn(AddProduct, \"P_MachineName\", each \"\", type text),",
                                                                                              "",
                                                                                              "    // ── 3.  Select only the final report columns ───────────────────────",
                                                                                              "    FinalColumns = Table.SelectColumns(AddMachineName, {",
                                                                                              "        \"A_UniqueId\", \"B_Criticality\", \"C_CveId\", \"C_CvssScore\",",
                                                                                              "        \"D_Description\", \"E_DeviceOS\", \"F_DeviceType\",",
                                                                                              "        \"G_DateFirstDetected\", \"H_DateLastDetected\",",
                                                                                              "        \"I_Status\", \"J_RiskAcceptance\",",
                                                                                              "        \"K_AssetCriticality\", \"L_DataType\", \"M_Location\",",
                                                                                              "        \"N_Notes\", \"O_Product\", \"P_MachineName\"",
                                                                                              "    }),",
                                                                                              "",
                                                                                              "    Renamed = Table.RenameColumns(FinalColumns, {",
                                                                                              "        {\"A_UniqueId\",          \"Unique ID\"},",
                                                                                              "        {\"B_Criticality\",       \"Criticality\"},",
                                                                                              "        {\"C_CveId\",             \"CVE#\"},",
                                                                                              "        {\"C_CvssScore\",         \"CVSS Score\"},",
                                                                                              "        {\"D_Description\",       \"Description\"},",
                                                                                              "        {\"E_DeviceOS\",          \"Device OS\"},",
                                                                                              "        {\"F_DeviceType\",        \"Device Type\"},",
                                                                                              "        {\"G_DateFirstDetected\", \"Date First Detected\"},",
                                                                                              "        {\"H_DateLastDetected\",  \"Date Last Detected\"},",
                                                                                              "        {\"I_Status\",            \"Status\"},",
                                                                                              "        {\"J_RiskAcceptance\",    \"Risk Acceptance\"},",
                                                                                              "        {\"K_AssetCriticality\",  \"Asset Criticality\"},",
                                                                                              "        {\"L_DataType\",          \"Data Type\"},",
                                                                                              "        {\"M_Location\",          \"Location\"},",
                                                                                              "        {\"N_Notes\",             \"Notes\"},",
                                                                                              "        {\"O_Product\",           \"Product\"},",
                                                                                              "        {\"P_MachineName\",       \"Machine Name\"}",
                                                                                              "    })",
                                                                                              "in",
                                                                                              "    Renamed"
                                                                                          ]
                                                                       }
                                                        }
                                                    ]
                                 }
                             ]
              }
}
